language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - mysql

before_install:
  - chmod +x mvnw

before_script:
  - mysql -u root -e 'CREATE DATABASE peminjaman;'
  - mysql -u root -e "CREATE USER 'peminjaman'@'localhost' IDENTIFIED BY 'peminjaman';"
  - mysql -u root -e "GRANT ALL ON peminjaman.* TO 'peminjaman'@'localhost';"